version: '3'
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.14.0
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /path/to/your/logs:/var/log/your_app:ro
    command: filebeat -e -strict.perms=false
    restart: unless-stopped
    network_mode: host
