name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Prepare POM for GitHub Packages
      run: |
        cp pom.xml pom.xml.orig
        sed -i 's/<groupId>ltd.shellapi.plugin<\/groupId>/<groupId>com.github.${{ github.repository_owner }}.shellapi.plugin<\/groupId>/' pom.xml

    - name: Publish to GitHub Packages
      run: |
        mvn deploy:deploy-file \
        -DpomFile=pom.xml \
        -Dfile=target/ShellApiLogOptimizer-0.0.1-SNAPSHOT.jar \
        -DrepositoryId=github \
        -Durl=https://maven.pkg.github.com/${{ github.repository }} \
        -DgeneratePom=false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Restore original POM
      run: mv pom.xml.orig pom.xml
